In [11]:
# NumPy Lab

import numpy as np

a = np.arange(1,10,2)
print(a)

b = np.ones((3,4))
print(b)

c = np.linspace(0,1,10)
print(c)

[1 3 5 7 9]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [13]:
arr1 = np.ones((3,4))

print(arr1)
print('size :', arr1.size)
print('dtype :', arr1.dtype)
print('shape :', arr1.shape)
print('ndim :', arr1.ndim)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
size : 12
dtype : float64
shape : (3, 4)
ndim : 2


In [23]:
# 1. A행령을 생성해보자.

A = np.array(
    [[1,2,3,4,5],
     [6,7,8,9,10],
     [11,12,13,14,15],
     [16,17,18,19,20],
     [21,22,23,24,25]]
    )

# 2. A의 모양(shape)을 출력해보자.

print(A.shape)

# 3. 19 값을 추출해보자.

print(A[3,3])

# 4. 슬라이싱을 이용하여 [[1,2], [6,7]] 값을 추출해보자.

print(A[:2,:2])

# 5. 슬라이싱을 이용하여 [[19,20], [24, 25]] 값을 추출해보자.

print(A[3:,3:])

# 6. 슬라이싱을 이용하여 0축의 첫 번째 행과 두 번째 행을 추출해보자.

# 7. 슬라이싱을 이용하여 1축의 마지막 열과 마지막 직전 열을 추출해보자.

(5, 5)
19
[[1 2]
 [6 7]]
[[19 20]
 [24 25]]


In [30]:
# 1. A행렬을 생성해보자.

A = np.arange(1,37)
A_R = A.reshape(3,3,4)
print(A_R)

# A 배열의 모양과 크기를 출력해보자.

print(A_R.shape, A_R.size)

# A 모양을 (3,4,3)로 변경해보자.

A_RR = A_R.reshape(3,4,3)
print(A_RR)

# A를 1차원 배열로 구성해보자
A_F = A_R.flatten()
print(A_F)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]
(3, 3, 4) 36
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
